import Navbar from '@/components/Navbar/Navbar';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import SupabaseProvider from '@/providers/SupabaseProvider';
import UserProvider from '@/providers/UserProvider';
import ModalProvider from '@/providers/ModalProvider';
import { ThemeProvider } from '@/components/theme-provider';
import KbarProvider from '@/components/Kbar/KbarProvide';
import Kbar from '@/components/Kbar/Kbar';
import ToasterProvider from '@/providers/ToasterProvider';
import getProjectsByOrder from '@/actions/getProjectsByOrder';
import { Layout } from 'lucide-react';
import LayoutComponent from './LayoutComponent';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} scrollbar scrollbar-thumb-gray-900 scrollbar-track-gray-100 text-[#d1ccc7] bg-[#191919] flex`}
      >
        <ThemeProvider defaultTheme='dark' attribute='class'>
          <ToasterProvider />
          <SupabaseProvider>
            <UserProvider>
              <LayoutComponent>{children}</LayoutComponent>
            </UserProvider>
          </SupabaseProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
