import Navbar from '@/components/Navbar/Navbar';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import SupabaseProvider from '@/providers/SupabaseProvider';
import UserProvider from '@/providers/UserProvider';
import ModalProvider from '@/providers/ModalProvider';
import KbarProvider from '@/components/Kbar/KbarProvide';
import Kbar from '@/components/Kbar/Kbar';
import { ThemeProvider } from '@/components/theme-provider';
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} text-[#d1ccc7] bg-[#191919] flex`}>
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
            <ThemeProvider attribute='class' defaultTheme='dark'>
              <KbarProvider>
                <Navbar />
                <Kbar />
                {children}
              </KbarProvider>
            </ThemeProvider>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
